include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    prefer_final_locals: true
    use_key_in_widget_constructors: true
    sort_child_properties_last: true
    always_declare_return_types: true
    unnecessary_this: false
    curly_braces_in_flow_control_structures: true
    unnecessary_brace_in_string_interps: true
    avoid_redundant_argument_values: true
    prefer_single_quotes: true

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
  errors:
    unused_import: warning
    dead_code: warning
    missing_required_param: error

